import Head from "next/head";
import Title from "../components/Title";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto">
        <Title text="Hello World" />
      </main>
    </div>
  );
}
